{"version":1,"defects":{"Tests\\Unit\\RouterTest::it_throws_unknown_uri_esception with data set #2":4,"Error":4,"Tests\\Unit\\RouterTest::it_throws_unknown_uri_esception with data set #0":4,"Tests\\Unit\\RouterTest::it_throws_unknown_uri_esception with data set #1":4,"Tests\\Unit\\RouterTest::it_throws_unknown_uri_esception with data set #3":4,"Tests\\Unit\\RouterTest::it_test_from_a_closure":4,"Tests\\Unit\\ContainerTest::it_checks_not_callable_case_for_get_without_setting":4},"times":{"Tests\\Unit\\RouterTest::it_registers_a_route":0.079,"Tests\\Unit\\RouterTest::it_throws_unknown_uri_esception with data set #0":0.103,"Tests\\Unit\\RouterTest::it_throws_unknown_uri_esception with data set #1":0,"Tests\\Unit\\RouterTest::it_throws_unknown_uri_esception with data set #2":0,"Tests\\Unit\\RouterTest::it_throws_unknown_uri_esception with data set #3":0,"Error":0.061,"Tests\\Unit\\RouterTest::it_test_from_a_closure":0.096,"Tests\\Unit\\RouterTest::it_tests_resolution_a_route":0.088,"Tests\\Unit\\ContainerTest::it_checks_has_function":0.115,"Tests\\Unit\\ContainerTest::it_checks_callable_case":0,"Tests\\Unit\\ContainerTest::it_checks_not_callable_case_for_get":0.023,"Tests\\Unit\\ContainerTest::it_checks_not_callable_case_for_get_without_setting":0,"Tests\\Unit\\ContainerTest::it_checks_not_callable_case_for_get_with_setting":0.02,"Tests\\Unit\\ContainerTest::it_checks_resolve_for_uninstantiable_class":0.056,"Tests\\Unit\\ContainerTest\\ContainerTest::it_checks_has_function":0.101,"Tests\\Unit\\ContainerTest\\ContainerTest::it_checks_callable_case":0,"Tests\\Unit\\ContainerTest\\ContainerTest::it_checks_not_callable_case_for_get_with_setting":0.024,"Tests\\Unit\\ContainerTest\\ContainerTest::it_checks_not_callable_case_for_get_without_setting":0,"Tests\\Unit\\ContainerTest\\ContainerTest::it_checks_resolve_for_uninstantiable_class":0.034,"Tests\\Unit\\ContainerTest\\ContainerTest::it_checks_resolve_without_constructor":0.006,"Tests\\Unit\\ContainerTest\\ContainerTest::it_checks_resolve_with_constructor":0.006}}